version: 2.1

jobs:
  build-and-test:
    docker:
      - image: 'quay.io/rohanpm/circleci-python:2.6'
    environment:
      CIRCLECI_PYTHON_EXECUTOR: python26
    steps:
      - checkout
      # - run:
      #     name: "Deadsnakes and Python2.6"
      #     command: |
      #       add-apt-repository ppa:deadsnakes/ppa
      #       apt-get update
      #       apt-get install python2.6 python2.6-dev
      - run:
          name: "Create TOX virtualenv"
          command: virtualenv TOX --python=`which python2.6`
      - run:
          command: ./TOX/bin/pip install tox --trusted-host pypi.org --trusted-host files.pythonhosted.org
          name: "Install tox in TOX venv"
      - run:
          command: ./TOX/bin/tox -c tox-py26.ini
          name: "Test against Python2.6"

workflows:
  main:
    jobs:
      - build-and-test
